language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libevent-2.0-5 libevent-openssl-2.0-5 libevent-dev php5-dev php5-cli
script: ./install-libwebsock.sh && phpize && ./configure && make
